apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-secrets-store-inline-wi
  labels:
    app: secrets-wi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-wi
  template:
    metadata:
      labels:
        app: secrets-wi
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: SERVICE_ACCOUNT_NAME
      containers:
      - name: secrets-wi
        image: registry.k8s.io/e2e-test-images/busybox:1.29-4
        command: ["/bin/tail"]
        args: ["-f", "/etc/passwd"]
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        imagePullPolicy: Always
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-wi"