apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-sp # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: KEYVAULT_NAME       # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: mysecret             # Set to the name of your secret
          objectType: secret               # object types: secret, key, or cert
    tenantId: IDENTITY_TENANT              # The tenant ID of the key vault 